CREATE TABLE TB_PRODUCT(
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250),
    BRAND VARCHAR(100) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    VALUE DECIMAL(18,2),
    ACTIVE BOOLEAN DEFAULT FALSE,
    CREATION_DATE TIMESTAMP(6) NOT NULL,
    UPDATE_DATE TIMESTAMP(6)
);