CREATE TABLE TB_BRAND (
    ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    FANTASY_NAME VARCHAR(100) NOT NULL,
    CORPORATE_NAME VARCHAR(100) NOT NULL,
    ACTIVE BOOLEAN DEFAULT FALSE,
    CREATE_DATE TIMESTAMP(6),
    UPDATE_DATE TIMESTAMP(6)
)